<?php

declare(strict_types=1);

namespace BVP\Scraper\Tests\Scrapers;

use Carbon\CarbonImmutable as Carbon;

/**
 * @psalm-import-type RaceArguments from \BVP\Scraper\Tests\ScraperPsalmType
 * @psalm-import-type RaceExpected from \BVP\Scraper\Tests\ScraperPsalmType
 *
 * @author shimomo
 */
final class ProgramScraperDataProvider
{
    /**
     * @psalm-return non-empty-list<
     *     array{
     *         arguments: RaceArguments,
     *         expected: RaceExpected,
     *     }
     * >
     *
     * @return array
     */
    public static function scrapeProvider(): array
    {
        return [
            [
                'arguments' => [Carbon::parse('2017-03-31'), 24, 1],
                'expected' => [
                    'date' => '2017-03-31',
                    'stadium_number' => 24,
                    'race_number' => 1,
                    'closed_at' => '2017-03-31 12:00:00',
                    'grade_number_source' => 'ippan',
                    'grade_number' => 5,
                    'title' => 'おおむら桜祭り競走',
                    'subtitle' => 'めざまし戦一般',
                    'distance_source' => '1800m',
                    'distance' => 1800,
                    'day_number_source' => '3日目',
                    'day_number' => 3,
                    'racers' => [
                        1 => [
                            'entry_number' => 1,
                            'name' => '中辻 博訓',
                            'number' => 3833,
                            'rank_number_source' => 'A1',
                            'rank_number' => 1,
                            'branch_number_source' => '福井',
                            'branch_number' => 18,
                            'birthplace_number_source' => '福井',
                            'birthplace_number' => 18,
                            'age_source' => '42歳',
                            'age' => 42,
                            'weight_source' => '54.0kg',
                            'weight' => 54.0,
                            'flying_count_source' => 'F1',
                            'flying_count' => 1,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.13,
                            'national_win_rate' => 6.45,
                            'national_top_2_percent' => 45.36,
                            'national_top_3_percent' => 65.98,
                            'local_win_rate' => 7.78,
                            'local_top_2_percent' => 55.56,
                            'local_top_3_percent' => 77.78,
                            'motor_number' => 66,
                            'motor_top_2_percent' => 88.89,
                            'motor_top_3_percent' => 100.0,
                            'boat_number' => 71,
                            'boat_top_2_percent' => 37.14,
                            'boat_top_3_percent' => 55.0,
                        ],
                        2 => [
                            'entry_number' => 2,
                            'name' => '津留 浩一郎',
                            'number' => 3773,
                            'rank_number_source' => 'B1',
                            'rank_number' => 3,
                            'branch_number_source' => '長崎',
                            'branch_number' => 42,
                            'birthplace_number_source' => '長崎',
                            'birthplace_number' => 42,
                            'age_source' => '42歳',
                            'age' => 42,
                            'weight_source' => '54.2kg',
                            'weight' => 54.2,
                            'flying_count_source' => 'F0',
                            'flying_count' => 0,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.18,
                            'national_win_rate' => 5.7,
                            'national_top_2_percent' => 35.85,
                            'national_top_3_percent' => 61.32,
                            'local_win_rate' => 6.4,
                            'local_top_2_percent' => 52.48,
                            'local_top_3_percent' => 65.35,
                            'motor_number' => 43,
                            'motor_top_2_percent' => 25.0,
                            'motor_top_3_percent' => 37.5,
                            'boat_number' => 41,
                            'boat_top_2_percent' => 28.87,
                            'boat_top_3_percent' => 40.14,
                        ],
                        3 => [
                            'entry_number' => 3,
                            'name' => '赤峰 和也',
                            'number' => 3471,
                            'rank_number_source' => 'B1',
                            'rank_number' => 3,
                            'branch_number_source' => '佐賀',
                            'branch_number' => 41,
                            'birthplace_number_source' => '佐賀',
                            'birthplace_number' => 41,
                            'age_source' => '47歳',
                            'age' => 47,
                            'weight_source' => '52.6kg',
                            'weight' => 52.6,
                            'flying_count_source' => 'F0',
                            'flying_count' => 0,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.21,
                            'national_win_rate' => 4.13,
                            'national_top_2_percent' => 16.5,
                            'national_top_3_percent' => 33.01,
                            'local_win_rate' => 3.95,
                            'local_top_2_percent' => 14.29,
                            'local_top_3_percent' => 33.33,
                            'motor_number' => 59,
                            'motor_top_2_percent' => 33.33,
                            'motor_top_3_percent' => 44.44,
                            'boat_number' => 67,
                            'boat_top_2_percent' => 30.71,
                            'boat_top_3_percent' => 50.71,
                        ],
                        4 => [
                            'entry_number' => 4,
                            'name' => '東 潤樹',
                            'number' => 4574,
                            'rank_number_source' => 'B1',
                            'rank_number' => 3,
                            'branch_number_source' => '広島',
                            'branch_number' => 34,
                            'birthplace_number_source' => '愛媛',
                            'birthplace_number' => 38,
                            'age_source' => '28歳',
                            'age' => 28,
                            'weight_source' => '51.2kg',
                            'weight' => 51.2,
                            'flying_count_source' => 'F1',
                            'flying_count' => 1,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.17,
                            'national_win_rate' => 4.88,
                            'national_top_2_percent' => 33.78,
                            'national_top_3_percent' => 41.89,
                            'local_win_rate' => 4.17,
                            'local_top_2_percent' => 13.04,
                            'local_top_3_percent' => 30.43,
                            'motor_number' => 73,
                            'motor_top_2_percent' => 37.5,
                            'motor_top_3_percent' => 50.0,
                            'boat_number' => 34,
                            'boat_top_2_percent' => 27.86,
                            'boat_top_3_percent' => 42.14,
                        ],
                        5 => [
                            'entry_number' => 5,
                            'name' => '牧 宏次',
                            'number' => 3800,
                            'rank_number_source' => 'B1',
                            'rank_number' => 3,
                            'branch_number_source' => '東京',
                            'branch_number' => 13,
                            'birthplace_number_source' => '神奈川',
                            'birthplace_number' => 14,
                            'age_source' => '43歳',
                            'age' => 43,
                            'weight_source' => '51.6kg',
                            'weight' => 51.6,
                            'flying_count_source' => 'F0',
                            'flying_count' => 0,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.2,
                            'national_win_rate' => 5.05,
                            'national_top_2_percent' => 34.48,
                            'national_top_3_percent' => 45.98,
                            'local_win_rate' => 5.0,
                            'local_top_2_percent' => 37.5,
                            'local_top_3_percent' => 37.5,
                            'motor_number' => 52,
                            'motor_top_2_percent' => 0.0,
                            'motor_top_3_percent' => 0.0,
                            'boat_number' => 65,
                            'boat_top_2_percent' => 39.57,
                            'boat_top_3_percent' => 56.83,
                        ],
                        6 => [
                            'entry_number' => 6,
                            'name' => '中北 涼',
                            'number' => 4924,
                            'rank_number_source' => 'B2',
                            'rank_number' => 4,
                            'branch_number_source' => '長崎',
                            'branch_number' => 42,
                            'birthplace_number_source' => '愛知',
                            'birthplace_number' => 23,
                            'age_source' => '24歳',
                            'age' => 24,
                            'weight_source' => '47.5kg',
                            'weight' => 47.5,
                            'flying_count_source' => 'F1',
                            'flying_count' => 1,
                            'late_count_source' => 'L0',
                            'late_count' => 0,
                            'average_start_timing' => 0.18,
                            'national_win_rate' => 1.76,
                            'national_top_2_percent' => 1.96,
                            'national_top_3_percent' => 1.96,
                            'local_win_rate' => 0.0,
                            'local_top_2_percent' => 0.0,
                            'local_top_3_percent' => 0.0,
                            'motor_number' => 64,
                            'motor_top_2_percent' => 66.67,
                            'motor_top_3_percent' => 88.89,
                            'boat_number' => 46,
                            'boat_top_2_percent' => 24.82,
                            'boat_top_3_percent' => 42.55,
                        ],
                    ],
                ],
            ],
            [
                'arguments' => [Carbon::parse('2019-10-14'), 2, 1],
                'expected' => [
                    'date' => '2019-10-14',
                    'stadium_number' => 2,
                    'race_number' => 1,
                    'closed_at' => null,
                    'grade_number_source' => null,
                    'grade_number' => null,
                    'title' => null,
                    'subtitle' => null,
                    'distance_source' => null,
                    'distance' => null,
                    'day_number_source' => null,
                    'day_number' => null,
                    'racers' => array_combine(
                        range(1, 6),
                        array_map(fn(int $entryNumber): array => [
                            'entry_number' => $entryNumber,
                            'name' => null,
                            'number' => null,
                            'rank_number_source' => null,
                            'rank_number' => null,
                            'branch_number_source' => null,
                            'branch_number' => null,
                            'birthplace_number_source' => null,
                            'birthplace_number' => null,
                            'age_source' => null,
                            'age' => null,
                            'weight_source' => null,
                            'weight' => null,
                            'flying_count_source' => null,
                            'flying_count' => null,
                            'late_count_source' => null,
                            'late_count' => null,
                            'average_start_timing' => null,
                            'national_win_rate' => null,
                            'national_top_2_percent' => null,
                            'national_top_3_percent' => null,
                            'local_win_rate' => null,
                            'local_top_2_percent' => null,
                            'local_top_3_percent' => null,
                            'motor_number' => null,
                            'motor_top_2_percent' => null,
                            'motor_top_3_percent' => null,
                            'boat_number' => null,
                            'boat_top_2_percent' => null,
                            'boat_top_3_percent' => null,
                        ], range(1, 6)),
                    ),
                ],
            ],
        ];
    }
}
